### PR TITLE
Updating C# Examples: Espresso, .mono and .vs.csproj

### PR DESCRIPTION
**Pull request by metadings**
Please, pickup my changes, and open a PR to imatix/zguide!

### CODE REVIEW

**Comment by metadings** [comment]
OHA there's the old shit in it... help... You need to manually copy things from `calid/zguide`, to the current `imatix/zguide`...

**Comment by calid** [comment]
Ok, I think I see... you just want the changes in 7297587? For the record, checking both parent branches of #600 it doesn't look like this was ever in zguide master?  So I don't think these changes were "lost."

Also I'm not sure if even 7297587 is ready for master... for example it removes examples/C#/README... why?

**Comment by metadings** [comment]
Yeah... Please, make your updates, I'm going to cleanup `zguide/examples/C#` the next week.

**Comment by calid** [comment]
> Please, make your updates

I'm not sure what you mean, why don't you just submit a PR for the C# changes you want in 7297587 to zguide master directly?

**Comment by metadings** [comment]
Ya, I'm going to do so. Looks correct now...

**Pull request closed without merging**
